### ISSUE TITLE
Missing MOODLE_INTERNAL Definition

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#10]
Hello,
I noticed that the MOODLE_INTERNAL check is missing in some files like: lib.php, locallib.php, etc.

Please ensure that each file includes the line:
`defined('MOODLE_INTERNAL') || die();  `
For more information, you can refer to the[ Moodle Coding Style Guide](https://moodledev.io/general/development/policies/codingstyle#require--include:~:text=defined(%27-,MOODLE_INTERNAL,-%27)%20%7C%7C).

![image](https://github.com/user-attachments/assets/a24d378c-5081-442e-a8c9-58d06cfcdbc3)
![image](https://github.com/user-attachments/assets/72bc3821-d4eb-4e40-a961-8b22aa02424d)

**Comment by weqon** [comment]
Thanks for your feedback.

We added the MOODLE_INTERNAL check.

The changes will be part of the next release.
