### ISSUE TITLE
Hard-coded language string

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#11]
Hello,

I noticed hard-coded language strings in the `helpfaq.mustache` file. All user-facing strings should be defined in the language file and displayed using the get_string() function.
https://moodledev.io/general/community/plugincontribution/checklist#strings 

![image](https://github.com/user-attachments/assets/5fc85b7c-f5dc-4cd2-b53b-04fa8c44b0e2)
![image](https://github.com/user-attachments/assets/ae0862c6-8d85-4ff0-9b7c-9002e4e70d7a)

**Comment by weqon** [comment]
Thanks for your feedback!

We wanted to move the site anyway and removed the template from the plugin.

This issue is therefore obsolete.
