### ISSUE TITLE
Incorrect CRUD value in events classes

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#12]
Hello,
I found incorrect CRUD values in some event classes. Please review and change this value to the corresponding action.

![image](https://github.com/user-attachments/assets/3de604ae-cc07-42a9-97c0-88f2f4c2f7f0)

**Comment by weqon** [comment]
Thanks for your feedback.

We adjusted the CRUD values for the events.

The changes will be part of the next release.
