### ISSUE TITLE
Deprecated constants usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#13]
Hello,
I found deprecated constant usage. Please review and change to the recommended replacement:

![image](https://github.com/user-attachments/assets/6ba6519d-ff91-47cd-aae2-3ec90fc7a4d8)

**Comment by weqon** [comment]
Thanks for your feedback!

We removed the deprecated constants and replaced them with the new one (https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/lib/upgrade.txt#L311).

The changes will be part of the next release.

FYI: Unfortunately, the deprecated constants are still mentioned in the Moodle documentation
https://moodledev.io/docs/4.5/apis/core/message#setting-defaults
