### ISSUE TITLE
Global SESSION usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#14]
Hello,
I found a global $SESSION usage in the code. As a recommendation, please consider using Moodle cache with MODE_SESSION mode. 
More details: https://moodledev.io/docs/4.5/apis/subsystems/muc
https://docs.moodle.org/dev/Cache_API_-_Quick_reference#:~:text=(cache_store%3A%3A-,MODE_SESSION,-%2C%20%27component%27

![image](https://github.com/user-attachments/assets/5bf88e4a-37b6-4400-9d5c-b9dc9c392879)

**Comment by weqon** [comment]
Thanks for your feedback!

We now implemented the Cache API and removed the old functions.

The changes will be part of the next release.
