### ISSUE TITLE
Use Namespaced CSS Selectors to Avoid Global Impact

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#15]
Hello,
I found CSS selectors in the styles.css file of the plugin that impact global HTML elements.

Please review the [Moodle Plugin Contribution Checklist](https://moodledev.io/general/community/plugincontribution/checklist#css-styles) for CSS requirements. Plugins must use properly namespaced selectors to ensure their stylesheets can be safely combined with others without affecting pages or elements beyond the plugin's scope.

Using plugin-specific CSS selectors is important to prevent accidental styling impacts on other parts of Moodle outside of your plugin’s scope.

![image](https://github.com/user-attachments/assets/6f3ccfa2-4c2c-47e7-bdc7-aacc34f2292f)

**Comment by weqon** [comment]
Thanks for your feedback.

We added plugin-specific CSS selectors.

The changes will be part of the next release.
