### ISSUE TITLE
Namespace collisions

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#16]
Hello,

According to Moodle standards, all custom classes that are not part of the core API should be placed in the 'classes/local' folder to avoid potential namespace collisions. You can refer to the guidelines here:
[Namespace Collisions - Moodle Plugin Checklist](https://moodledev.io/general/community/plugincontribution/checklist#namespace-collisions)
Please review the rules for level 2 namespaces:
[Level 2 Namespaces](https://moodledev.io/general/development/policies/codingstyle#rules-for-level2)

Additionally, all functions in localliib.php file should be prefixed in frankestyle format:
https://moodledev.io/general/development/policies/codingstyle/frankenstyle#function-names

![image](https://github.com/user-attachments/assets/89390826-f1a5-48a0-8a2a-95ca4fefbc9d)
![image](https://github.com/user-attachments/assets/eb82680b-fd46-45f2-b5ec-60bc660945d6)

**Comment by weqon** [comment]
Thanks for your feedback.

We adjusted the namespace and added the frankenstyle prefix to the functions in locallib.php
The changes will be part of the next release.

To the H5P "canedit.php": Please check this issue
https://github.com/weqon/moodle-local_eportfolio/issues/3#issuecomment-2461419942

Once we remove the class or move it to another location, Moodle throws an error, that the file can't be edited.

The class "canedit" will be called by the H5P API here:
https://github.com/moodle/moodle/blob/MOODLE_401_STABLE/h5p/classes/api.php#L292

In case we are missing something here, please advise.
