### ISSUE TITLE
Incorrect repository name

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#17]
Hello,
based on the naming convention for Moodle plugins, the repository name should match the pattern: `moodle-{plugintype}_{pluginname}`.

For guidance, you can refer to the following documentation:
[Code repository name](https://moodledev.io/general/community/plugincontribution/checklist#code-repository-name)

This is not a strong requirement, just an option to provide a consistent experience for other Moodle developers.

**Comment by weqon** [comment]
Thanks for your feedback.

We adjusted the repository name.
