### ISSUE TITLE
file name

### ISSUE THREAD

**Issue by eduardokraus** [weqon/moodle_local_eportfolio#2]
The file https://github.com/weqon/moodle_local_eportfolio/blob/MOODLE_401_STABLE/classes/forms/sharing_form.php is named `sharing_form`, but the class is called `sharing_form_1`.

**Comment by weqon** [comment]
Thanks for your feedback!

We splitted the sharing form classes into separate files .

https://github.com/weqon/moodle_local_eportfolio/commit/f5f1a3a944242db0f835d4712024da433f61f4d0
