### ISSUE TITLE
Detecting and Removing Unused Variables and Classes

### ISSUE THREAD

**Issue by eduardokraus** [weqon/moodle_local_eportfolio#3]
There are unused variables and classes.

![Captura de Tela 2024-10-31 às 19 09 43](https://github.com/user-attachments/assets/b28e7c58-56b4-4e22-8a6b-99567413f0a7)
![Captura de Tela 2024-10-31 às 19 09 51](https://github.com/user-attachments/assets/8527b6f7-503c-43fe-b89a-1a0d9f4b4fc1)

**Comment by weqon** [comment]
Thanks for your feedback!

We removed the unused $CFG from classes/forms/upload_form.php.
https://github.com/weqon/moodle_local_eportfolio/blob/MOODLE_401_STABLE/classes/forms/upload_form.php#L44

The classes/h5p/canedit.php is required by the plugin. Otherwise we can't use the H5P editor.
