### ISSUE TITLE
Suggested Update for `access.php` Permission Key

### ISSUE THREAD

**Issue by eduardokraus** [weqon/moodle_local_eportfolio#5]
In `access.php`, should the value `"local/eportfolio:view_eport"` be `"local/eportfolio:view_report"` instead?

![Captura de Tela 2024-10-31 às 19 18 19](https://github.com/user-attachments/assets/695b9287-9c0c-4e32-800c-540b454b6cb5)

**Comment by weqon** [comment]
Thanks for your feedback!

"eport" is the working title for this plugin and is the right term in this context.
