### ISSUE TITLE
Missing Required Dependency for `mod_eportfolio` in `version.php`

### ISSUE THREAD

**Issue by eduardokraus** [weqon/moodle_local_eportfolio#6]
In the file `classes/forms/sharing_form.php`, the `mod/eportfolio:grade_eport` capability is called, but the `version.php` does not list `mod_eportfolio` as a required dependency.

![Captura de Tela 2024-10-31 às 19 20 50](https://github.com/user-attachments/assets/d7c36839-2f8c-49bb-8467-87663a9ea1b4)
![Captura de Tela 2024-10-31 às 19 21 00](https://github.com/user-attachments/assets/97a46c17-3792-4fe5-8120-f57556eadc72)

**Comment by weqon** [comment]
Thanks for your feedback!

The dependency was fixed and is now part of classes/forms/sharing_form_3.php.

[https://github.com/weqon/moodle_local_eportfolio/issues/2](https://github.com/weqon/moodle_local_eportfolio/issues/2)

https://github.com/weqon/moodle_local_eportfolio/blob/MOODLE_401_STABLE/classes/forms/sharing_form_3.php
