### ISSUE TITLE
Error when trying to delete the plugin

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#7]
Hello,
I got an error when tried to delete the plugin with the admin panel:

![image](https://github.com/user-attachments/assets/1db4c0c0-42e6-4f34-b9dd-af636fc8f050)

**Comment by weqon** [comment]
Thanks for your feedback.

We fixed this part and successfully tested the deinstallation process.

The changes will be part of the next release.
