### ISSUE TITLE
Hard coded role ids

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#8]
Hello,
It is not a good practice to use hard-coded role IDs. In some systems, IDs can be completely different and it is better to use role archetypes to get needed roles.

![image](https://github.com/user-attachments/assets/ab325862-5bd1-4d9d-bc37-3b438eb9e437)
![image](https://github.com/user-attachments/assets/5b9a6079-03ca-48b9-9c78-b2b3e9cd87a3)

This is more as a recommendation, but not requirement.

**Comment by weqon** [comment]
Thanks for your feedback!

We removed this part from the install.php.

After successful installation, the admin is redirected to the settings page anyway and thus has the option of making the necessary settings directly. 

The changes will be part of the next release.
