### ISSUE TITLE
Missing variables definitions in Privacy provider

### ISSUE THREAD

**Issue by volodymyrdovhan** [weqon/moodle_local_eportfolio#9]
Hello,
I found an issue with not defined $context variable in Privacy provider class:
![image](https://github.com/user-attachments/assets/32b99474-9878-405a-8123-6ee49c886d87)

In addition, I would like to recommend to validate Privacy API implementation with CLI Tools or unit tests:
https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils

**Comment by weqon** [comment]
Thanks for your feedback and also for the hint with the CLI tools!

We reworked the privacy provider.

The changes will be part of the next release.
